### PR TITLE
Frequent

### PR DESCRIPTION
**Pull request by CatalystCoder**
This code worked when I ran it through repl it but it doesn't seem to work when I run rake. Any suggestions? Thanks! _Update_ I noticed an error I made and when I tried to fix it I believe I broke something because it won't let me push it. I tried to delete the initial post but I think that broke it.

### CODE REVIEW

**Comment by sumeetjain** [comment]
What's the current status of this? I'm having trouble figuring out what your question is (If any).

**Comment by CatalystCoder** [comment]
Sorry about the confusion on this one. I realized a few things after I submitted the pull request. It's still a work in progress.

**Comment by sumeetjain** [comment]
I see that your 'comment' was "Assistance". Are you asking for help? I'd like a more specific question if you are. (If you're not asking for help and just wanted to indicate that this is still a work in progress, then no problem–carry on.)

**Comment by CatalystCoder** [comment]
It is officially completed!

**Comment by sumeetjain** [comment]
:+1:

**Pull request closed without merging**
