### PR TITLE
Done

### PR DESCRIPTION
**Pull request by mel-d**
This works well to find the most frequent integer when there IS one most frequent integer. However, I haven't had any success yet trying to figure out how to return nil when there isn't any one integer that's more frequent than all the others. Any clues for what I could try?

(The [0] at the end of the return line is just so that only the key and not the value shows up. Is this an acceptable way to do that? Or is there a better way to return only the key from a hash set?)

I've been Googling both of these questions to no avail!

### CODE REVIEW

**Comment by sumeetjain** [comment]
Consider the following hash, where the values represent how many times the associated key appears. So it's kind of like the `h` hash that you make in your code.

``` ruby
{
  "banana" => 4,
  "apple" => 3,
  "orange" => 4,
  "pear" => 2
}
```

If I asked you what the highest frequency in that hash is, what would you say? (You would hopefully say `4`.) And how would you find that value using code? Is there a way to determine the highest value in a hash using Ruby? (That's google-able.)

If you figure that out, then you'll have a hash with elements and their frequencies and also the highest frequency that's in that hash. So now you need to check if more than one element in the hash has that value, because if more than one does you should `return nil`.

**Else** you should return whatever element in the hash has that key, because it's the most frequent element.

Let me know if this isn't helpful.

---

Re: your other question–

> The [0] at the end of the return line is just so that only the key and not the value shows up. Is this an acceptable way to do that? Or is there a better way to return only the key from a hash set?

That's a good way to do it.

**Comment by mel-d** [comment]
I understand what you said in your feedback, and that's what I'm trying to do, but I keep getting stuck on little things (which I'm probably just over-thinking because my brain is scrambled). I've finally figured out a way for the program to loop through all keys in the hash. What I'm trying to do is get my output_hash to work with the .uniq method, and I keep getting errors, even though I've tried it with multiple {} methods I've found on Google. Once I can get output_hash to delete its duplicated and return only one of each key-value pair, I'll add something like "if output_hash has more than one key, return nil; else, return key". Like I said, though, I'm just stuck on getting .uniq to work.

**Comment by mel-d** [comment]
One more thing: I know we're not supposed to use puts in these exercises, but when I use return instead the code stops looping after the first key-hash pair.

**Comment by mel-d** [comment]
I got some help from a friend and am nearly there; I'm just getting one error with Cloud9, but it seems a bit strange that I'm getting the result I wanted on repl.it and a different result on Cloud9. Hopefully this will be ok. See you Monday!

**Comment by mel-d** [comment]
Two errors, actually:  
1) Failure:
MultiplyTest#test_empty_set [/home/ubuntu/workspace/tests/most_frequent_integer_test.rb:23]:
Expected: nil
  Actual: []

  2) Failure:
MultiplyTest#test_base_case [/home/ubuntu/workspace/tests/most_frequent_integer_test.rb:9]:
Expected: 1
  Actual: ["1"]

**Comment by sumeetjain** [comment]
:+1:

**Pull request closed without merging**
